spring.application.name=crm-backend

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/crmdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate=DEBUG

server.port=8080